version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8000"

  product-service:
    build: ./product-service
    ports:
      - "8002:8000"

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
